In [34]:
import numpy as np

arr = np.array([2, 4, 6, 8, 7])
a = [5, 6]
print(len(arr))
print(arr[1:3])
print(arr.sum())
a.append(7)
print(7*a)
arr.std()
# np.mean(arr)

5
[4 6]
27
[5, 6, 7, 5, 6, 7, 5, 6, 7, 5, 6, 7, 5, 6, 7, 5, 6, 7, 5, 6, 7]


2.1540659228538015

In [11]:
def sqr(x):
  return x*x 

def cube(x):
  return x*x*x 

(sqr(5),cube(5))

(25, 125)

In [15]:
area = lambda x,y,z: x*y*z
area(5,6,7)

210

In [21]:
def isPrime(x): 
  return x % 2 == 0 or False
another = [i+1 for i in range(7) if isPrime(i+1)]
print(another)

[2, 4, 6]


In [32]:
first = np.ones(5, dtype='int')
sec = np.ones(5, dtype='int')
first + sec 

array([2, 2, 2, 2, 2])

In [42]:
ex = np.random.random([4, 4])
print(ex)
print(ex[1:3, 0:3])

[[0.36210988 0.99719    0.24144438 0.49643633]
 [0.55963779 0.60844952 0.36300137 0.18640674]
 [0.78949016 0.5161901  0.92192692 0.8280738 ]
 [0.64747452 0.87329235 0.2298447  0.1409305 ]]
[[0.55963779 0.60844952 0.36300137]
 [0.78949016 0.5161901  0.92192692]]
